# Generated by Django 4.2.2 on 2024-10-14 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Address1',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Address2',
            new_name='address2',
        ),
    ]
