# Generated by Django 4.2.2 on 2024-10-14 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_address1_profile_address1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Phone',
            new_name='phone',
        ),
    ]
