# Generated by Django 4.2.2 on 2024-10-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_profile_old_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default='uploads/category/main.jfif', upload_to='uploads/category'),
        ),
    ]
